### PR TITLE
return `NoResourceVersion` error if resource version is empty

### LINKED ISSUE #1251: Strengthen `resource_version` handling in `watcher`
As a follow-up to #1250 , there are two things we should tweak to strengthen guarantees and improve usability;

- in `Empty` phase; treat empty string resource versions as equivalent to missing (to return the NoResourceVersion error) - via https://github.com/kube-rs/kube/pull/1250#issuecomment-1635368925
- in `Watching` phase; swap resource version uwraps for an unwrap_or_default and return NoResourceVersion error if it's empty

Currently we have treated missing resource versions as a hard error (crash-worthy even), and while it is an [invariant they assume and verify in tests](https://github.com/kube-rs/kube/pull/1250#issuecomment-1634910581), we have an error case ready for this. We should not crash and instead bubble up the `NoResourceVersion` error.

### PR DESCRIPTION
**Pull request by aryan9600**
## Motivation
Atm, the watcher don't check if the returned resource version is empty before taking its next step, which effectively makes it a hard error (potential panics since we use `unwrap()` in some places). Instead of treating them as hard errors, we should bubble them up.

## Solution
Check if resource version returned by the API to the watcher is empty and return a `NoResourceVersion` error if it is.

Fixes #1251

### CODE REVIEW

File: kube-runtime/src/watcher.rs [hunk 1]
```diff
@@ -467,18 +469,26 @@ where
...
         } => match stream.next().await {
             Some(Ok(WatchEvent::Added(obj) | WatchEvent::Modified(obj))) => {
-                let resource_version = obj.resource_version().unwrap();
-                (Some(Ok(Event::Applied(obj))), State::Watching {
-                    resource_version,
-                    stream,
-                })
+                let resource_version = obj.resource_version().unwrap_or_default();
+                if resource_version.is_empty() {
+                    (Some(Err(Error::NoResourceVersion)), State::default())
```
Comment (clux) [inline kube-runtime/src/watcher.rs:474]: One minor observation here. Before this change in the watching stage, we would actually be somewhat resilient to missing resource versions here (where resource versions got transmitted as empty strings) because the resource version is only used in the next watch, and Kubernetes seem to accept empty strings in the watch params 🙃 

It is __technically possible__ that this change will lead to more re-lists because of some apiserver returning "" as resource versions. Still, that's kind of an impossibly defensive game to play against what is meant to be a stable api, so it's probably best to assume they are reasonably well behaved here, and raise bugs upstream otherwise.

**Review by clux — APPROVED** [review]
Thank you! Nice and simple. One of the last unwrap assumptions in the runtime gone 👍 

Left a comment on a potential error case this __could in theory introduce__, but I feel it's probably not anything worth worrying about.

File: kube-runtime/src/watcher.rs (hunk 1 above)
Comment (aryan9600) [reply kube-runtime/src/watcher.rs:474]: yes its theoretically possible, but as far as i'm aware, this should practically not happen since the resource version in the response is never blank. From https://kubernetes.io/docs/reference/using-api/api-concepts/#resourceversion-in-metadata:
> v1.meta/ListMeta - The metadata.resourceVersion of a resource collection (the response to a list) identifies the resource version at which the collection was constructed.
