### PR TITLE
fix(predicate): track resource UID to handle recreated resources

### LINKED ISSUE #1830: Recreated objects do not pass through predicate filters
### Current and expected behavior

```rust
    let (reader, writer) = reflector::store();
    let stream = reflector(writer, watcher(api, watcher::Config::default()))
        .default_backoff()
        .applied_objects()
        .predicate_filter(predicates::generation);

    Controller::for_stream(stream, reader)
```

Using a predicate (such as `generation`) filter, events are dropped for objects which are replaced (create-delete-create) in scenarios where the replaced object is the same (according to the filter alone). In other words, using the `generation` filter, if you delete and recreate a resource with the same generation, the new resource will not pass through the filter even though it is a new / distinct resource at that time.

For example:

1. Create resource (`generation=1`), controller reconciles
2. Delete resource
3. Recreate resource (`generation=1`), controller does not reconcile
4. Edit resource (`generation=2`), controller reconciles

IMO, this is a bug because the resources in (1) and (3) are actually distinct (different `metadata.uid`). Consider that the controller is responsible for managing some operand (e.g. `Deployment`). Using owner references and garbage collection, the `Deployment` would be deleted as part of (2). I would expect the `Deployment` to be recreated at (3), but it is not due to the predicate filter.

### Possible solution

The predicate cache could consider a resource's `uid` as part of the key hashing algorithm.

### Additional context

This appears to be due to kube's `ObjectRef` type not considering `extra` for its `Hash` impl, as `ObjectRef` is the key for the `Predicate` cache (`HashMap`).

```rust
pub struct ObjectRef<K: Lookup + ?Sized> {
    // ...

    /// Extra information about the object being referred to
    ///
    /// This is *not* considered when comparing objects, but may be used when converting to and from other representations,
    /// such as [`OwnerReference`] or [`ObjectReference`].
    #[educe(Hash(ignore), PartialEq(ignore))]
    pub extra: Extra,
}
```

I'm guessing there was a specific reason this `extra` data was ignored in the `Hash` impl (perhaps memory footprint / overhead for deleted objects?). However, it leads to (imo) unintuitive behavior in the predicate filter implementation so may be worth reconsidering or using a different type for the cache.

### Environment

OCP 4.18

### Configuration and features

```toml
k8s-openapi = { version = "0.25", features = ["latest", "schemars"] }
kube = { version = "1", features = [
    "runtime",
    "derive",
    "client",
    "unstable-runtime",
] }
```

### YAML

_No response_

### Affected crates

kube-runtime

### Would you like to work on fixing this bug?

maybe

### PR DESCRIPTION
**Pull request by doxxx93**
## Description

Fixes #1830

Resources recreated with the same name/namespace but different UIDs were incorrectly filtered out by the predicate filter. This PR fixes the issue by tracking UIDs in the cache to distinguish between different resource instances.

## Problem

When using predicate filters (e.g., `predicates::generation`), if a resource is:
1. Created (generation=1, uid=A)
2. Deleted
3. Recreated (generation=1, uid=B)

The recreated resource would be incorrectly filtered out because the cache only used `ObjectRef` as the key, which deliberately excludes UID from its Hash implementation.

This caused controllers to miss reconciliation of recreated resources, breaking scenarios where resources need to be managed via owner references and garbage collection.

## Solution

Created a new `PredicateCacheKey` struct that includes UID in the cache key:
```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct PredicateCacheKey {
    name: String,
    namespace: Option<String>,
    uid: Option<String>,
}
```

Modified `PredicateFilter` cache from:
```rust
HashMap<ObjectRef<K>, u64>
```

to:
```rust
HashMap<PredicateCacheKey, u64>
```

This ensures different resource instances (with different UIDs) are treated as separate cache entries.

## Changes

- Added `PredicateCacheKey` struct that includes UID in equality/hashing
- Modified `PredicateFilter` cache to use `PredicateCacheKey` instead of `ObjectRef`
- Updated `poll_next` to create cache keys that include UID
- Added regression test `predicate_filtering_should_handle_recreated_resources_with_same_generation`

## Testing

All existing tests pass (67 passed), including new regression test that verifies:
- First resource with UID "uid-1" passes through
- Recreated resource with same generation but different UID "uid-2" also passes through (previously would be filtered out)

```bash
cargo test --package kube-runtime --lib
```

## Checklist

- [x] Fixed the bug described in #1830
- [x] Added regression test
- [x] All tests pass
- [x] Commit signed with DCO (--signoff)
- [x] No breaking API changes

### CODE REVIEW

**Comment by doxxx93** [comment]
i will fix lint soon

File: kube-runtime/src/utils/predicate.rs [hunk 1]
```diff
@@ -103,7 +103,7 @@ pub struct PredicateFilter<St, K: Resource, P: Predicate<K>> {
     #[pin]
     stream: St,
     predicate: P,
-    cache: HashMap<ObjectRef<K>, u64>,
+    cache: HashMap<ObjectRef<K>, (Option<String>, u64)>,
```
Comment (clux) [inline kube-runtime/src/utils/predicate.rs]: one good thing about this being private is that we can change this without any problems.

i do wonder if it's simpler to have a specific alternative (private) `ObjectRef` here with an equality that takes into account `uid`. that way the poll_next logic would remain pretty simple afaikt? wdyt?

**Review by clux — COMMENTED** [review]
thanks a lot for this!

i have one comment initially because it solves it in a way i did not expect, but it's all private implementation details. i just want to make it as simple as possible 😄

File: kube-runtime/src/utils/predicate.rs (hunk 1 above)
Comment (doxxx93) [reply kube-runtime/src/utils/predicate.rs]: I think you're absolutely right!

which one do you prefer **private struct implementation** like:

```rust
/// Private cache key that includes UID in equality for predicate filtering
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct PredicateCacheKey {
  name: String,
  namespace: Option<String>,
  uid: Option<String>,
}

// poll_next logic:
let key = PredicateCacheKey {
  name: obj.meta().name.clone().unwrap_or_default(),
  namespace: obj.meta().namespace.clone(),
  uid: obj.meta().uid.clone(),
};
let changed = me.cache.get(&key) != Some(&val);
```

Or **tuple implementation** like:
```
cache: HashMap<(ObjectRef<K>, Option<String>), u64>

// poll_next logic:
let key = (ObjectRef::from_obj(&obj), obj.meta().uid.clone());
let changed = me.cache.get(&key) != Some(&val);
```

Both approaches include UID in the cache key equality,

keep poll_next logic simple. 

What do you think works better for this codebase?

Comment (doxxx93) [reply kube-runtime/src/utils/predicate.rs]: Let me know if I'm misunderstanding your suggestion

Comment (clux) [reply kube-runtime/src/utils/predicate.rs]: I like your first suggestion there the best, feels cleaner than the tuple. You could also have a `From<&ObjectMeta>` impl for `PredictCacheKey` in that case to separate the logic from the poll body.

(One thing that we will need as a follow-up (probably outside this PR) is to think about TTL of cache keys now, because it was always a case that the predicate cache had an unbounded growth, and with this it's more likely. EDIT: raised https://github.com/kube-rs/kube/issues/1837 for a follow-up)

Comment (doxxx93) [reply kube-runtime/src/utils/predicate.rs]: Done! Refactored to use `PredicateCacheKey` with `From<&ObjectMeta>` impl. The poll logic is much cleaner now.

Good point about the cache TTL - I see you've opened #1837 for follow-up. Happy to help with that in a separate PR if needed.

Which style do you prefer, or would you like me to adjust it?

**Comment by doxxx93** [comment]
hum.. sorry for lint

File: kube-runtime/src/utils/predicate.rs [hunk 2]
```diff
@@ -134,17 +155,9 @@ where
...
-                            true
-                        };
-                        if let Some(old) = me.cache.get_mut(&key) {
-                            *old = val;
-                        } else {
-                            me.cache.insert(key, val);
-                        }
+                        let key = PredicateCacheKey::from(obj.meta());
+                        let changed = me.cache.get(&key) != Some(&val);
+                        me.cache.insert(key, val);
```
Comment (clux) [inline kube-runtime/src/utils/predicate.rs:161]: nice cleanup. i guess this will call `.insert` always now even if it was found, but that is fine because it's a hashmap [`::insert`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.insert) will just update the value and keys have a proper `Eq`.

File: kube-runtime/src/utils/predicate.rs [hunk 3]
```diff
@@ -251,4 +264,51 @@ pub(crate) mod tests {
...
+                }
+            }))
+            .unwrap();
+            p
+        };
+
+        // Simulate: create (gen=1, uid=1) -> delete -> create (gen=1, uid=2)
+        let data = stream::iter([
+            Ok(mkobj(1, "uid-1")), // First resource created, generation=1
+            Ok(mkobj(1, "uid-2")), // Resource recreated with same generation but different UID
```
Comment (clux) [inline kube-runtime/src/utils/predicate.rs]:
```suggestion
            Ok(mkobj(1, "uid-2")), // Resource recreated with same generation but different UID
            Ok(mkobj(2, "uid-2")), // Recreated resource with new generation
```

feel like we should add one more case to ensure the normal case flows through for uid handling

File: kube-runtime/src/utils/predicate.rs [hunk 4]
```diff
@@ -103,7 +122,8 @@ pub struct PredicateFilter<St, K: Resource, P: Predicate<K>> {
     #[pin]
     stream: St,
     predicate: P,
-    cache: HashMap<ObjectRef<K>, u64>,
+    cache: HashMap<PredicateCacheKey, u64>,
+    _phantom: PhantomData<K>,
```
Comment (clux) [inline kube-runtime/src/utils/predicate.rs:127]:
```suggestion
    // K: Resource necessary to get .meta() of an object during polling
    _phantom: PhantomData<K>,
```
for my later sanity

File: kube-runtime/src/utils/predicate.rs (hunk 1 above)
Comment (clux) [reply kube-runtime/src/utils/predicate.rs]: Style is great. Let's get this thing in first, then if you want to look at the follow-up let's look at that after. Resolving.

File: kube-runtime/src/utils/predicate.rs (hunk 3 above)
Comment (doxxx93) [reply kube-runtime/src/utils/predicate.rs]: thanks for advice

File: kube-runtime/src/utils/predicate.rs [hunk 5]
```diff
@@ -251,4 +265,60 @@ pub(crate) mod tests {
...
+        assert_eq!(first.meta().uid.as_deref(), Some("uid-1"));
+
+        // Second object (same UID, same generation) should be filtered out - no event
+        // Third object should pass through because it's a different resource
+        // (different UID), even though it has the same generation
+        let second = rx.next().now_or_never().unwrap().unwrap().unwrap();
+        assert_eq!(second.meta().generation, Some(1));
+        assert_eq!(second.meta().uid.as_deref(), Some("uid-2"));
+
+        // Fourth object should also pass through because it's a different resource
```
Comment (clux) [inline kube-runtime/src/utils/predicate.rs]: This comment is confusing as there is no 4th resource

Comment (doxxx93) [reply kube-runtime/src/utils/predicate.rs]: thanks

Comment (doxxx93) [reply kube-runtime/src/utils/predicate.rs]: updated comments like `predicate_filtering_hides_equal_predicate_values` test's comment style
