### PR TITLE
Fix potentially panicing unchecked duration adds in runtime

### LINKED ISSUE #1488: Unchecked add of instant + duration is causing a panic.
### Current and expected behavior

https://github.com/kube-rs/kube/blob/0.91.0/kube-runtime/src/controller/mod.rs#L475

I'm getting a panic here.  I'm sure it's because we've accidentally queued up some long retry duration, but it shouldn't panic even if you do that.  Digging through the code, there's actually quite a few unchecked additions of times in the code.

### Possible solution

use checked adds.

### Additional context

_No response_

### Environment

We're using the latest version of EKS 1.29, but i don't think it's relevant.

### Configuration and features

_No response_

### Affected crates

kube-runtime

### Would you like to work on fixing this bug?

None

### PR DESCRIPTION
**Pull request by clux**
Fixes #1488. Searched a lot and found 3 legit cases.

Prevents pathological overlows of `Instant` + `Duration` with now() defaulted use of [`Instant::checked_add`](https://doc.rust-lang.org/std/time/struct.Instant.html#method.checked_add)

### CODE REVIEW

File: kube-runtime/src/controller/mod.rs [hunk 1]
```diff
@@ -472,7 +472,9 @@ where
                     obj_ref,
                     reason: reschedule_reason,
                 },
-                run_at: reconciler_finished_at + requeue_after,
+                run_at: reconciler_finished_at
+                    .checked_add(requeue_after)
+                    .unwrap_or_else(Instant::now),
```
Comment (Dav1dde) [inline kube-runtime/src/controller/mod.rs:477]: If this overflows, it would be so far in the future that it practically never runs, right? -> It shouldn't be queued for now, but for never?

Comment (clux) [reply kube-runtime/src/controller/mod.rs:477]: Yeah, maybe. Not sure how to represent that though, nor if it is wise to try to represent this in the scheduler: if people don't want the reconcile to hit they maybe shouldn't return a requeue.

I'm also not sure if there is some other monotonicity reason here that could cause the panic.

Comment (Dav1dde) [reply kube-runtime/src/controller/mod.rs:477]: I actually remembered that I've investigated this before ... [tokio](https://github.com/tokio-rs/tokio/blob/6fcd9c02176bf3cd570bc7de88edaa3b95ea480a/tokio/src/time/instant.rs#L57-L63) handles it this way, so the default could be 30 years in the future.

Comment (clux) [reply kube-runtime/src/controller/mod.rs:477]: ah nice! yeah `Instant::far_future` is probably a better default here if there is no other way it can fail.

if they told us to use enormous requeue values, then it's kind of expected that we never get around to running it (and we will always override with the smallest instant here for other changes, so should be safe)

**Review by Dav1dde — APPROVED** [review]
