### PR TITLE
Remove conflicting additionalProperties: false from schema

### LINKED ISSUE #1828: CRD generation with `#[serde(deny_unknown_fields)]` applies both `additionalProperties` and `properties`
### Current and expected behavior

Consider the following CRD:

```rust
#[derive(CustomResource, Deserialize, Serialize, Clone, Debug, JsonSchema)]
#[kube(
    kind = "MyCRD",
    group = "example.com",
    version = "v1",
    namespaced
)]
pub struct MyCRDSpec {
    pub subitem: SubItemDenyUnknown,
}

#[derive(Deserialize, Serialize, Clone, Debug, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SubItemDenyUnknown {
    pub one: String,
    pub two: bool,
    pub three: i32,
}
```

When `#[serde(deny_unknown_fields)]` is specified, this generates a CRD with both a `additionalProperties: false`, and `properties:` of the `SubItemDenyUnknown` object itself:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.example.com
spec:
  group: example.com
  names:
    categories: []
    kind: MyCRD
    plural: mycrds
    shortNames: []
    singular: mycrd
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MyCRDSpec via `CustomResource`
        properties:
          spec:
            properties:
              subitem:
                additionalProperties: false
                properties:
                  one:
                    type: string
                  three:
                    format: int32
                    type: integer
                  two:
                    type: boolean
                required:
                - one
                - three
                - two
                type: object
            required:
            - subitem
            type: object
        required:
        - spec
        title: MyCRD
        type: object
    served: true
    storage: true
    subresources: {}
```

Because this object already contains properties, I would expect `additionalProperties` to not be specified here as it results in a Kubernetes CRD validation error:

```console
Forbidden: additionalProperties and properties are mutual exclusive
```

### Possible solution

I saw a similar issue in https://github.com/kube-rs/kube/issues/844. I am not sure if a similar fix is applicable here. I think omitting `additionalProperties: false` entirely might be more applicable (see context).

### Additional context

The [CRD Validation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) page in the Kubernetes docs states:

> The field `additionalProperties` cannot be set to `false`.

It doesn't seem like this returns an error though, as I tried applying this CRD which applied successfully but pruned the `additionalProperties: false` from the actual applied CRD. The CRD I applied:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycrds.example.com
spec:
  group: example.com
  names:
    categories: []
    kind: MyCRD
    plural: mycrds
    shortNames: []
    singular: mycrd
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MyCRDSpec via `CustomResource`
        properties:
          spec:
            properties:
              one:
                type: string
              two:
                type: object
                additionalProperties: false
            required:
            - one
            type: object
        required:
        - spec
        title: MyCRD
        type: object
    served: true
    storage: true
    subresources: {}
```

And this is what ended up on my cluster:

```yaml
spec:
  conversion:
    strategy: None
  group: example.com
  names:
    kind: MyCRD
    listKind: MyCRDList
    plural: mycrds
    singular: mycrd
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for MyCRDSpec via `CustomResource`
        properties:
          spec:
            properties:
              one:
                type: string
              two:
                type: object
            required:
            - one
            type: object
        required:
        - spec
        title: MyCRD
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: MyCRD
    listKind: MyCRDList
    plural: mycrds
    singular: mycrd
  conditions:
  - lastTransitionTime: "2025-09-25T06:25:43Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-09-25T06:25:43Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
```

### Environment

I am running with `kind`, using a regular `kind create cluster`:

```console
Client Version: v1.33.4
Kustomize Version: v5.6.0
Server Version: v1.33.1
```

### Configuration and features

```toml
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
kube = { version = "2.0.1", features = ["runtime", "client", "derive"] }
```

### YAML

_No response_

### Affected crates

_No response_

### Would you like to work on fixing this bug?

yes

### PR DESCRIPTION
**Pull request by doxxx93**
## Motivation

fix  #1828

When generating Custom Resource Definitions (CRDs) with `kube-derive` for structs using `#[serde(deny_unknown_fields)] `(or similar mechanisms that result in additionalProperties: false), the generated OpenAPI v3 schema can become invalid according to Kubernetes validation rules. 

Kubernetes considers additionalProperties and properties to be mutually exclusive when both are present, leading to validation errors like "Forbidden: additionalProperties and properties are mutual exclusive" upon CRD creation/update. 

## Solution

The `StructuralSchemaRewriter` in kube-core has been updated to explicitly remove `additionalProperties: false` from object schemas when properties are also defined. 

This aligns the generated schema with Kubernetes' behavior, where unknown fields are pruned by default if `x-kubernetes-preserve-unknown-fields` is not set to true. This change ensures that CRDs generated with kube-derive for structs using `#[serde(deny_unknown_fields)]` are valid and accepted by the Kubernetes API server. 

The logic for handling `additionalProperties: true` (converting to `x-kubernetes-preserve-unknown-fields: true`) remains unchanged.

### CODE REVIEW

File: kube-core/src/schema.rs [hunk 1]
```diff
@@ -347,14 +347,21 @@ impl Transform for StructuralSchemaRewriter {
...
-            && !object.properties.is_empty()
-            && object.additional_properties.as_deref() == Some(&Schema::Bool(true))
-        {
-            object.additional_properties = None;
-            schema
-                .extensions
-                .insert("x-kubernetes-preserve-unknown-fields".into(), true.into());
+        if let Some(object) = &mut schema.object {
+            if !object.properties.is_empty() {
+                match object.additional_properties.as_deref() {
```
Comment (clux) [inline kube-core/src/schema.rs]: let's move the old comment up to reference this line specifically so we don't conflate the two different fixes later

```suggestion
            // check for maps without with properties (i.e. flattened maps)
            // and allow these to persist dynamically
                match object.additional_properties.as_deref() {
```

Comment (doxxx93) [reply kube-core/src/schema.rs]: thx! It's better looking

**Review by clux — APPROVED** [review]
looks good, thanks!
